backend:
  name: git-gateway
  branch: develop
  squash_merges: true
  commit_messages:
    create: 'feat({{collection}}): create {{collection}} “{{slug}}”'
    update: 'feat({{collection}}): update {{collection}} “{{slug}}”'
    delete: 'feat({{collection}}): delete {{collection}} “{{slug}}”'

media_folder: static/images

collections:
  - label: 'Components'
    name: 'components'
    files:
      - label: 'Accordion'
        name: 'accordion'
        file: 'src/ec/packages/ec-component-accordion/README.md'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Example, name: example, widget: code }
          - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
