backend:
  name: github
  repo: ec-europa/ecl-twig
  open_authoring: true
  branch: netlifycms
  squash_merges: true
  commit_messages:
    create: 'feat({{collection}}): create {{collection}} “{{slug}}”'
    update: 'feat({{collection}}): update {{collection}} “{{slug}}”'
    delete: 'feat({{collection}}): delete {{collection}} “{{slug}}”'
    uploadMedia: 'Upload “{{path}}”'
    deleteMedia: 'Delete “{{path}}”'

media_folder: static/images
publish_mode: editorial_workflow

collections:
  - label: 'Components'
    name: 'components'
    files:
      - label: 'Accordion'
        name: 'accordion'
        file: 'src/ec/packages/ec-component-accordion/README.md'
        fields:
          - { label: ECL-Twig Doc, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
